# This is a basic workflow to help you get started with Actions

name: Push To NuGet

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore
      run: dotnet restore --configuration Release

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --output .
      working-directory: ./src/Sg4Mvc
    
    #- name: Push
    #  run: dotnet nuget push SG4MVC.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
    #  env: 
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
