# This is a basic workflow to help you get started with Actions

name: Push To NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version in the format 1.1.1-beta'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    #- name: Push
    #  run: dotnet nuget push SG4MVC.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
    #  env: 
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
