# This is a basic workflow to help you get started with Actions

name: Push To NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'version in the format 1.1.1-beta'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --output .
      working-directory: ./src/Sg4Mvc
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: ./src/Sg4Mvc/SG4MVC.${{ github.event.inputs.version }}.nupkg
        retention-days: 1
      
    - name: Push
      run: dotnet nuget push ./src/Sg4Mvc/SG4MVC.${{ github.event.inputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env: 
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
